#server.port=8083
#
#  # MySQL数据库连接配置
#spring.datasource.url=jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
server:
  port: 8080
spring:
  jpa:
    open-in-view: off
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/zhiliao?serverTimezone=Hongkong&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  mvc:
    #    static-path-pattern: /**
    view:
      #前缀
      prefix: /
      #后缀
      suffix: .html
  #  resources:
  #    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html

#  security:
#    user:
#      name: user
#      password: 123
mybatis:
  type-aliases-package: edu.dwlx.entity

#  configuration:
#    environment:
#    database-id:
#    map-underscore-to-camel-case: true
